/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

/**
 *
 * @author Nirmith Akash
 */
public class Border extends javax.swing.JFrame {

    /**
     * Creates new form Border
     */
    public Border() {
        initComponents();
        
        //When starting the frame load the pannel
        
        MainMenuPanel h1 = new MainMenuPanel();
        LayeredPane1.removeAll();
        h1.setSize(LayeredPane1.getSize());
        LayeredPane1.add(h1);
        h1.setVisible(true);
        LayeredPane1.moveToFront(h1);
    }
    
    public static void changeFunction(String name){
        //If condition
        if (name.contentEquals("Kitchen")) {
            Home h1 = new Home();
            LayeredPane1.removeAll();
            h1.setSize(LayeredPane1.getSize());
            LayeredPane1.add(h1);
            h1.setVisible(true);
            LayeredPane1.moveToFront(h1);
            System.out.println("Triggered");

        } else if (name.contentEquals("Home")) {
            MainMenuPanel h1 = new MainMenuPanel();
            LayeredPane1.removeAll();
            h1.setSize(LayeredPane1.getSize());
            LayeredPane1.add(h1);
            h1.setVisible(true);
            LayeredPane1.moveToFront(h1);

        }
        //Add other functions here 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        LayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LayeredPane1.setMaximumSize(new java.awt.Dimension(1360, 590));
        LayeredPane1.setMinimumSize(new java.awt.Dimension(1360, 590));

        javax.swing.GroupLayout LayeredPane1Layout = new javax.swing.GroupLayout(LayeredPane1);
        LayeredPane1.setLayout(LayeredPane1Layout);
        LayeredPane1Layout.setHorizontalGroup(
            LayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        LayeredPane1Layout.setVerticalGroup(
            LayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        back.add(LayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1360, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Web1366–3.png"))); // NOI18N
        back.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Border.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Border.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Border.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Border.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Border().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLayeredPane LayeredPane1;
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
